# Generated by Django 4.1.7 on 2023-03-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'customer', 'verbose_name_plural': 'customer'},
        ),
    ]
