# Generated by Django 4.1.7 on 2023-03-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinfo',
            name='avater',
            field=models.ImageField(default=True, upload_to='avater'),
        ),
    ]
